server.port=8080
spring.cloud.gateway.enabled=true

# --- Konfigurasi Route 1 ---
spring.cloud.gateway.routes[0].id=route_service1
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/service1/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/service1/(?<segment>.*), /service1/${segment}


# --- Konfigurasi Route 2 (Tugas Anggota 3) ---
spring.cloud.gateway.routes[1].id=route_service2
spring.cloud.gateway.routes[1].uri=http://localhost:8082 
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/service2/**
# Ini wajib ada sesuai instruksi
spring.cloud.gateway.routes[1].predicates[1]=Method=GET 
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/service2/(?<segment>.*), /service2/${segment}


# testing
jwt.secret=testing_token_rahasia_untuk_tugas_anggota_empat_kelompok_tujuh

