server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: route_one_base
          uri: http://localhost:8080
          predicates:
            - Path=/service1/**

        - id: route_two_base
          uri: http://localhost:8080
          predicates:
            - Path=/service2/**